### Login
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "username": "superstats",
  "password": "test123"
}

### Logout (requires token from login response)
POST http://localhost:5001/api/auth/logout
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN_HERE


### Get All Orders (Protected)
GET http://localhost:5001/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJzdXBlcnN0YXRzIiwiaWF0IjoxNzU3NjU3Mzc0LCJleHAiOjE3NTc2NjA5NzR9.OH2JcAaV_sML9GADU4WSRth0hVHH_SgdGEKn4E9AWJs

### Get All Orders (Protected)
GET http://localhost:5001/api/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJzdXBlcnN0YXRzIiwiaWF0IjoxNzU3NjU3Mzc0LCJleHAiOjE3NTc2NjA5NzR9.OH2JcAaV_sML9GADU4WSRth0hVHH_SgdGEKn4E9AWJs


### Get All Categories (Protected)
GET http://localhost:5001/api/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJzdXBlcnN0YXRzIiwiaWF0IjoxNzU3NjU3Mzc0LCJleHAiOjE3NTc2NjA5NzR9.OH2JcAaV_sML9GADU4WSRth0hVHH_SgdGEKn4E9AWJs