### Login
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "username": "superuser",
  "password": "superuser"
}

### Just GET
GET http://localhost:5001/

### Logout (requires token from login response)
POST http://localhost:5001/api/auth/logout
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN_HERE


### Get All Orders (Protected)
GET http://localhost:5001/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJzdXBlcnN0YXRzIiwiaWF0IjoxNzU3NjYxNzE1LCJleHAiOjE3NTc2NzI1MTV9.OUwhZyk9SM2g0tIUiBD29qxJeECNheT-bScyYyR-hv8

### Get All Orders (Protected)
GET http://localhost:5001/api/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJzdXBlcnN0YXRzIiwiaWF0IjoxNzU3NjYxNzE1LCJleHAiOjE3NTc2NzI1MTV9.OUwhZyk9SM2g0tIUiBD29qxJeECNheT-bScyYyR-hv8

### Get All Categories (Protected)
GET http://localhost:5001/api/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJzdXBlcnN0YXRzIiwiaWF0IjoxNzU3NjYxNzE1LCJleHAiOjE3NTc2NzI1MTV9.OUwhZyk9SM2g0tIUiBD29qxJeECNheT-bScyYyR-hv8

### Get All Sales per Product (Protected)
GET http://localhost:5001/api/sales_per_product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJzdXBlcnVzZXIiLCJpYXQiOjE3NTg3ODM5NzMsImV4cCI6MTc1ODc5NDc3M30.lLiFvKaQpZE_vWo4dG2t2IE_ZWCC4s1egKdT0ZfFiKg

### Get All Sales per Category (Protected)
GET http://localhost:5001/api/sales_per_category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJzdXBlcnN0YXRzIiwiaWF0IjoxNzU3NzY2MzA1LCJleHAiOjE3NTc3NzcxMDV9.n_8er9vSDj4bLlgxfW8h7HrneOCOeAsdTc4soSMd4jk

### Get VAT (Protected)
GET http://localhost:5001/api/vat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJzdXBlcnVzZXIiLCJpYXQiOjE3NTgwMDg3MjMsImV4cCI6MTc1ODAxOTUyM30.XQM80Aw-gsHGIrGxEleVWefwPSsPrVgHDNsQbFmPRns